import subprocess
import tempfile
import unittest


class TemplateSmokeTests(unittest.TestCase):
    def test_classify_blocked_pages(self) -> None:
        import main

        self.assertEqual(
            main._classify_page("Access denied. Sorry, you have been blocked! Cloudflare Ray ID ..."),
            "blocked",
        )
        self.assertEqual(
            main._classify_page("403 ERROR\nRequest blocked.\nGenerated by cloudfront (CloudFront)"),
            "blocked",
        )
        self.assertEqual(
            main._classify_page("Something went wrong! Our best minds are on this, please refresh or come back later"),
            "blocked",
        )

    def test_classify_location_gated(self) -> None:
        import main

        self.assertEqual(main._classify_page("Select Location\nLogin/ Sign Up"), "location-gated")
        self.assertEqual(main._classify_page("Detect my location"), "location-gated")

    def test_js_templates_are_valid_js(self) -> None:
        import main

        blinkit_js = main._blinkit_extraction_js("milk")
        generic_js = main._generic_extraction_js("zepto", "milk")

        with tempfile.TemporaryDirectory() as td:
            p1 = td + "/blinkit.js"
            p2 = td + "/generic.js"
            with open(p1, "w", encoding="utf-8") as f:
                f.write(blinkit_js)
            with open(p2, "w", encoding="utf-8") as f:
                f.write(generic_js)

            # node --check parses JS without running it (no DOM needed).
            r1 = subprocess.run(["node", "--check", p1], capture_output=True, text=True)
            r2 = subprocess.run(["node", "--check", p2], capture_output=True, text=True)
            self.assertEqual(r1.returncode, 0, r1.stderr or r1.stdout)
            self.assertEqual(r2.returncode, 0, r2.stderr or r2.stdout)


if __name__ == "__main__":
    unittest.main()

